### ISSUE TITLE
Unable to update using Kisak's Repo

### ISSUE THREAD

**Issue by Casuallynoted** [ValveSoftware/SteamVR-for-Linux#191]
```
E: The repository 'http://ppa.launchpad.net/kisak/steamvr/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

Getting this error when trying to use Kisak's Repo

**Comment by kisak-valve** [comment]
Hello @Casuallynoted, SteamVR Experimental Graphics currently does not have any 18.10 (cosmic) packages, only 18.04. Because the primary goal is to have a reliable test environment for development and having debug symbols for kernels is relatively huge, only Ubuntu LTS is planned for now due to the PPA size limit.

For the individual parts, SteamVR on AMD should be fine with linux 4.16+, xorg 1.20.1 (and DDX built against it), and a recent mesa release.
