### ISSUE TITLE
Controller Settings / rebindings window doesn't open

### ISSUE THREAD

**Issue by FictionX** [ValveSoftware/SteamVR-for-Linux#217]
**Your system information**
Steam client version (build number or date): Jul 18, 2019
Distribution (e.g. Ubuntu): Ubuntu 19.04
Graphics driver version (run nvidia-settings): 430.26
Gist for SteamVR System Information: 
https://gist.github.com/FictionX/bc3abd07dcc587494ddf4daf43721ee1
Opted into Steam client beta?: [Yes/No] Yes
Opted into SteamVR beta?: [Yes/No] Yes
Have you checked for system updates?: [Yes/No] Yes

**Please describe your issue in as much detail as possible:**

When selecting Devices / Controller Settings in SteamVR (beta 16.8 or stable), the controller settings window doesn't open. 

**Steps for reproducing this issue:**
Select Devices / Controller Settings in SteamVR on the desktop. A window should open - it does not.

**Comment by kisak-valve** [comment]
Hello @FictionX, this interface should need vrwebhelper to render. It was temporarily disabled in [SteamVR Beta 1.5.6](https://steamcommunity.com/gid/103582791435040972/announcements/detail/1602632798036185257) due to general stability issues.

You should be able to test this component by adding `STEAMVR_WEBHELPER=1 %command%` to SteamVR's launch options.

**Comment by Zamundaaa** [comment]
So I just tried it and it's a mess. It spawned about 15 vrwebhelper processes, opened two windows and it crashed SteamVR as well as Steam.

**Comment by FictionX** [comment]
Thanks @kisak-valve . I forgot about that. I guess Skyrim VR is off the playlist until this has been fixed.

I tried STEAMVR_WEBHELPER=1 %command%, but had the same issues as Zamundaaa.

**Comment by Zamundaaa** [comment]
If you need to change the bindings, you can also use http://localhost:8998/dashboard/controllerbinding.html in the browser.
Oh and for safety: when it crashed for me, the display stayed on or turned on again after the crash... You should probably double check that, burnin isn't fun.

**Comment by FictionX** [comment]
@Zamundaaa Thanks a lot!

**Comment by Zamundaaa** [comment]
Still crashes. Spawns a few empty windows, and lots of vrwebhelper processes that do nothing but use 1% of the CPU. The SteamVR window says 
Headset Error
Make sure your headset's display is in fullscreen mode
Enable fullscreen mode (-202)
This is especially bad as having webvrhelper enabled is the only way to _disable_ Async Reprojection, which is sadly currently necessary in order to play Pavlov comforably.

**Comment by Zamundaaa** [comment]
This works reliably for me now.
