### ISSUE TITLE
Vivecraft stuck on Index screen

### ISSUE THREAD

**Issue by acul009** [ValveSoftware/SteamVR-for-Linux#378]
#### Your system information
* Steam client version (build number or date):  July 24th 2020
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): 440.100
* Gist for SteamVR System Information: https://gist.github.com/acul009/668838eb5f3f0e6ae2d5275d6ad94866
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes (but normal one doesn't work either)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I installed Vivecraft and wanted to play, but the headset gets stuck on the last frame of the loading screen and steamvr takes over and handles rotation until the main menu open, where my problem begins.
The last loading screen frame gets show the entire time, while the desktop mirror works fine and tracks the headset. SteamVR also displays frame timings that look plausible and even the controllers are being tracked and can be used to navigate the menus.

I'm not sure if this is a steamvr issue, but I'm not sure how to interpret the log files, so I hope you can help me.
These are the 3 logfiles who mention java (searched using grep):
https://gist.github.com/acul009/48399b57797669147586ffb15fa280ed#file-vrclient_java-txt
https://gist.github.com/acul009/48399b57797669147586ffb15fa280ed#file-vrcompositor-txt
https://gist.github.com/acul009/48399b57797669147586ffb15fa280ed#file-vrserver-txt

I'm happy for all the help I can get :)
Please tell me if you need anything else.

#### Steps for reproducing this issue:
1. Install minecraft and vivecraft
2. Launch steamvr
3. Launch vivecraft
4. observe as the headset get's stuck, but the spectator window is fine

**Comment by jrbudda** [comment]
Just to add some details as the dev of Vivecraft:

Vivecraft (Minecraft) is OpenGL.

We've narrowed the problem down to the deletion of the eye textures. On Windows there is no issue with generating a new texture id and submitting to SteamVR. There is still the  issue of new textures must be the same *size* as the first texture ever submitted but that's been a known OpenGL/Steamvr thing even on Windows since the beginning.

We've found (mostly accidentally) that deleting (glDeleteTextures) the eye texture id first submitted to steamvr causes that eye to freeze in the compositor, even if a new texture id is later submitted.

Not calling glDeleteTextures on the first texid allows that eye to continue to display normally, even when generating and submitting a new texture id.

My gut feeling is that SteamVR is remembering the first texid it receives for each eye, and even tho it is not necessarily using that texid for the compositor rendering, it is attempting to query something about it, such that if the original texid is deleted the compositor fails for that eye. This is just a guess and we have not exhaustively tested it.

**Comment by jrbudda** [comment]
After more digging this seems to be https://github.com/ValveSoftware/openvr/issues/1255 this issue. The linux gpu driver is immediately releasing the texid's when deleting the textures and the subsequent call to genTextures is returning the just-released id. I'd think a submit flag to tell the compositor to flush any cached information would solve it.

**Comment by SpookySkeletons** [comment]
@jrbudda Is there any dirty mesa hack/patch to fix the problem possible?
