### ISSUE TITLE
[BUG] No sound output to Valve Index

### ISSUE THREAD

**Issue by CTJansson** [ValveSoftware/SteamVR-for-Linux#446]
**Describe the bug**
I have no sound on my Valve Index, the sound output is my normal headphones

**To Reproduce**
1. Install steam vr
2. Install beat saber
3. Install latest mesa, vulkan and so on
4. Config up steam vr, standing only
5. Play steamvr/beat saber
6. Hello darkness my old friend (sound of silence if you didn't .. ye I see myself out)

**Expected behavior**
I expect to get sound out of my VR Headset instead of my headphones

**System Information (please complete the following information):**
- Distribution: EndeavourOS (Arch-based)
- SteamVR version: 1.17.10
- Steam client version: May 10 2021, at 01:54:04, package versions: 1621394999
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 21.1.1
- Gist for SteamVR System Information: https://gist.github.com/CTJansson/73918f04a2aad7d232b2af6661bd88a4

**Screenshots**
![image](https://user-images.githubusercontent.com/8863468/119403177-37cee680-bcde-11eb-8462-ad8be13376dd.png)

**Additional context**
I can't find any sound output that seems to be the Valve Index, only for microphone, check image above for my output devices, Xonar DX, HDA ATI HDMI are my screens (no additional port than HDMI / DispalyPort), Starship/Mattise I assume this is my on-board audio.

I have also tried this on Ubuntu 21.04, exactly the same issue, windows 10 works perfectly so there is no problem with my index or computer.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ZarathustraDK** [comment]
You have to go to the "Configuration"-tab in the window (upper center/right of the picture), in there you can configure which HDMI/DisplayPort-port your card uses for output. It will of course differ depending on which port you use for the HMD. Best way to figure out: Start beatsaber and get to the main-menu (there will be music playing there), then try out the different ports for your card under the Configuration-tab until you hear something.

When you figure out, memorize the port, you'll have to set it each time you start SteamVR because the port disappears and become invisible to pulseaudio every time you turn off SteamVR (and resets to some other available source/output.

There's probably some way to script it, at least I remember seeing some once, but couldn't get it to work, so I just set it every time.

**Comment by aaaantoine** [comment]
The workaround given by @ZarathustraDK worked for me... But it seems to me that if SteamVR is firing up, it should set the OS playback device to whichever HDMI port the HMD is plugged into.  Right?

In other words, I'm not sure that this issue should be closed just yet.

**Comment by c-x-berger** [comment]
Commenting because I had this issue too and this thread appeared in DuckDuckGo: Make sure udev rules are set exactly as described in the README! That got things working for me (as in, I was able to change the port my card was using to the Index).
