### ISSUE TITLE
[BUG] Fallout 4 VR with Script Extender and FRIK crashes on black screen regardless of Proton Version

### ISSUE THREAD

**Issue by 6ooflames** [ValveSoftware/SteamVR-for-Linux#498]
I'm trying to use Fallout 4 VR with Script Extender and FRIK, but it crashes on the initial black screen regardless of which Proton Version im using. I've tried 6.3-8, 7.0-1 and Proton 7.1 and 7.2 GE.

1. Install F4SEVR and FRIK and dependencies
2. Rename Fallout4VR.exe to Fallout4.exe and f4se_loader.exe to Fallout4VR.exe and add `[Loader] RuntimeName=Fallout4.exe` to Data/f4sevr.ini
3. Launch SteamVR & Fallout 4 VR

On Windows, [people](https://youtu.be/9A01mcBYXZI) have  gotten it working...

System Information:
- Distribution: [Manjaro]
- SteamVR version: [E.g. 1.20.4]
- Steam client version: [Jan 16 2022, at 17:34:49] 
- Opted into Steam client beta?: [No]
- Graphics driver version:  NVIDIA 510.47.03
- Gist for SteamVR System Information: https://gist.github.com/6ooflames/66c76b1f871c55a9d05180fa8304c381

**Comment by kisak-valve** [comment]
Hello @6ooflames, we're tracking issues with games run with Proton in the Proton issue tracker, and this issue has already been reported at https://github.com/ValveSoftware/Proton/issues/1069, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1069#issuecomment-1046331729.

**Comment by 6ooflames** [comment]
This is not a duplicate of [https://github.com/ValveSoftware/Proton/issues/1069](https://github.com/ValveSoftware/Proton/issues/1069), as F4SE initialises successfully and even loads FRIK.dll and FO4VRTools.dll correctly. Should I open a new Proton issue report instead?

**Comment by kisak-valve** [comment]
In general, we're also using one issue per unofficially supported game title on the Proton issue tracker, but in this specific case Skyrim VR and Fallout 4 VR got mashed together. If the older feedback is simply outdated, then it's probably fine where it is, but worth adding a note there, otherwise it'd make sense to split those two games apart if there's different behavior between them. It's also preferred to discuss mods in the same compatibility report as the unaltered game release.

Not the clearest advice given that you're focused on game modding instead of the game by itself, but that's the general intent.
