### ISSUE TITLE
Unreal 4.16 doesn't detect HTC Vive / SteamVR in Ubuntu: "VR Preview" greyed out

### ISSUE THREAD

**Issue by jessedubord** [ValveSoftware/SteamVR-for-Linux#55]
#### Your system information
* Steam client version (build number or date): May 26, 2017
* Distribution (e.g. Ubuntu): Ubuntu GNOME 17.04 x64
* Graphics driver version (run nvidia-settings): Nvidia 381.22
* Gist for SteamVR System Information: [https://gist.github.com/jessedubord/cd07e067d48e74a676c91b574b6aa39d](url)
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
BEHAVIOR
When running Unreal Engine 4.16, creating a VR game, opening the sample projects, and attempting to preview them in VR using the HTC Vive, you can't, the options are greyed out. I checked on the Unreal forums, and they said it had to do with SteamVR software (see here: [https://forums.unrealengine.com/showthread.php?138679-4-15-0-SteamVR-and-Linux-Ubuntu-quot-VR-Preview-quot-greyed-out&p=714532#post714532](url)).

![screenshot from 2017-05-25 13-18-43](https://cloud.githubusercontent.com/assets/11955519/26514713/65c5bd28-4228-11e7-9d21-664c8a97576c.png)
("VR Preview" option is greyed out)

EXPECTED BEHAVIOR
To be able to test in-game levels using the Unreal Engine 4.16 with HTC Vive and SteamVR in Linux.

#### Steps for reproducing this issue:
1. Start SteamVR beta program
2. Start Unreal Engine (I did from a Terminal)
3. Create a new VR project, then open a sample scene/map/level to test
4. Click on the drop-down arrow next to Unreal's big "Play" button at the top, then try to select "VR Preview".

**Comment by TTimo** [comment]
Can you package the test project and see if that will run in VR? You may need to pass -vr on the command line when starting the packaged project.

**Comment by jessedubord** [comment]
@TTimo , I'm still a considerable novice at Unreal -- been taking things one step at a time. :) I'll absolutely try and see if I can compile, package and run the test and see if it runs stand-alone on Ubuntu, then report back.

**Comment by jessedubord** [comment]
@TTimo, I was finally able to build and package a Linux version of the test VR levels that come with Unreal 4.16.1 for HTC Vive. I ran the built project in Terminal (both with and without the "-vr" parameter), but the level wouldn't register the HTC Vive. SteamVR showed no indication that a VR app was running.

**Comment by TTimo** [comment]
I suggest starting SteamVR from steam before you launch your game (rather than relying on the game doing the launch).

You may also need to execute your game within the Steam runtime environment. This is done by using the runtime's run.sh script to start your game (~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh).

Note that even once you get this working, performance of SteamVR+OpenGL on Linux is still going to be pretty poor due to it going through slow paths in the compositor (this affects Linux specifically, not Windows). The better option is to use Vulkan but UE4 doesn't have stable support for SteamVR+Vulkan just yet.

**Comment by jessedubord** [comment]
Sorry, I should have mentioned that I did start SteamVR before trying to launch the game. It was already active.

I'll test by running the run.sh script and report back.

I'm assuming the issue you wrote about explains the latency in programs like the new Steam Home app and others?

**Comment by vrhaptics** [comment]
I am using CentOS7 with Unreal  4.16.1 editor. I am facing the same issue of VR Preview grayed ot. I have launched steamVR and all the headset, controllers and base stations are showing green which means that all are up and running. After launching steamVR, I launched UE 4.16.1 editor ,  in the plugins, steamvr is enabled. But still the VR preview is grayed out. Any help to resolve the issue is appreciated.

**Comment by TTimo** [comment]
I was able to reproduce this problem of 'VR Preview' greyed out and identify the correct solution. You need to start the editor within the Steam runtime environment:

`~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./Engine/Binaries/Linux/UE4Editor-Linux-Debug /opt/Valve/TestVR/TestVR.uproject -opengl4 -sm5`

(TestVR is a test VR map out of the starter content)

It will 'work' in the sense that 'VR Preview' won't be greyed out anymore. Performance will be terrible because the GL path is sub-optimal, and you will likely run into other bugs besides that.

If you don't launch the editor in the steam runtime environment, VR Preview will be greyed out.

**Comment by vrhaptics** [comment]
Thanks for your valuable suggestion. It works. Further, can you please suggest me on the steps to improve the performance. Thanks in advance.

**Comment by TTimo** [comment]
You will need to wait for this: https://github.com/KhronosGroup/OpenGL-Registry/pull/65

More specifically the extensions need to make their way into the GL drivers (NVidia and radeonsi), and SteamVR will need to roll out the support to leverage it.

Alternatively you can also keep an eye on UE4's SteamVR+Vulkan support which will bypass those GL issues - but in this case more work in UE4 is needed for support and stability.

**Comment by kkriehl** [comment]
NVIDIA just released [a new Vulkan](https://developer.nvidia.com/vulkan-driver) driver that implements the new extensions.

**Comment by vrhaptics** [comment]
Thanks a lot for the info
