### ISSUE TITLE
[BUG] AMD Radeon RX 7900 XTX - Unable To Drive Valve Index At 144Hz

### ISSUE THREAD

**Issue by gekret005** [ValveSoftware/SteamVR-for-Linux#552]
**Describe the bug**
In SteamVR when the Valve Index is set to 144Hz it will proceed to fail. Setting it to 80, 90, and 120 all seem to work fine. The same occurs under Windows 10 and 11.

**To Reproduce**
Set Valve Index to 144hz 
**Expected behavior**
Valve Index Runs at 144Hz

**System Information:**
- Distribution: Gentoo
- SteamVR version: 1.25.1
- Steam client version: Mon Dec 19
- Opted into Steam client beta?: Yes
- Graphics driver version:  : Mesa 23.0.0-devel (git-9bb1d8ab19)
- Gist for SteamVR System Information: https://gist.github.com/gekret005/7d69775e4e6dd3aa947633857ea815fd
**Attached files:**
[vrcompositor.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/10286704/vrcompositor.txt)
[dmesg.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/10286706/dmesg.txt)

**Related Issues**
Also posted at https://gitlab.freedesktop.org/drm/amd/-/issues/2310
https://steamcommunity.com/app/250820/discussions/3/3723945543093550005/

**Comment by Danielduel** [comment]
Same issue,
happens only with vulkan-radeon, using amdvlk doesn't crash (although I can't tell if the output is full 144Hz).
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/532 seems like the same issue.

Differences:
latest Arch with X11 gnome
steamvr beta 1.25.3
steam build Dec 15 2022
5950X cpu

@gekret005 since you have very close stack to mine, do you get artifacts on the "border" of right eye (and artifacted 2d surfaces in steamvr overlays (but not in the 3d scenes))
![Screenshot from 2023-01-31 22-13-02](https://user-images.githubusercontent.com/8364951/216047857-39760d81-9fcc-4cfd-b53d-0201629281e2.png)
The artifacting is random, usually it is pure white with random distorted gpu memory trash(?).
In the headset the artifact is visible only if your eye is very close to the lens, but since it is very bright white - it is a bit unpleasant to play.

**Comment by kisak-valve** [comment]
Hello @Danielduel, please give #480 a read.

**Comment by Danielduel** [comment]
> Hello @Danielduel, please give #480 a read.

Wow, I didn't knew how to look for that issue, thank you a ton <3

**Comment by Defense-Matrix** [comment]
I also have this problem with my 7900xtx. The 144hz one

**Comment by kzdixon** [comment]
If you want to get the fix early, this kernel branch tag has it fixed: https://gitlab.freedesktop.org/agd5f/linux/-/tags/amd-drm-next-6.3-2023-02-17
The fix does not seem to be merged in as of kernel `6.2`.

**Comment by ZarathustraDK** [comment]
Just chiming in with the same experience. Upgraded from a 6800XT that had the 144Hz option to a 7900 XTX that seems to be lacking it.

**Comment by kzdixon** [comment]
I'm guessing it should be merged in when we get 6.3.

**Comment by Meister1593** [comment]
Had this issue with vive randomly not getting into direct mode for a while
Just tested 6.3 kernel on fedora silverblue (see here how to do it https://coreos.github.io/rpm-ostree/ex-replace) on arch container with steam and it worked perfectly, vive now can be detected every time

**Comment by 143mailliw** [comment]
On my 7900XT I can't even select any refresh rate. It just says "Additional refresh rates are supported by your HMD, but were not detected by the graphics driver.". Running mesa-git and the amd-drm-next tree.

**Comment by kzdixon** [comment]
Fix has been merged as of kernel 6.3+.

**Comment by BillGR17** [comment]
Yeah, it works for me too now

**Comment by Danielduel** [comment]
Headset doesn't crash anymore with 144Hz selected, will check if it's stable today.

**Comment by Danielduel** [comment]
Seems stable, 3h of (proton) Beat Saber on 144Hz index ran without any problems, the difference to 120Hz is hard to spot, but I would argue it correctly pushed frames.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
