### ISSUE TITLE
Location of Steam Runtime not accurate in README.md?

### ISSUE THREAD

**Issue by jessedubord** [ValveSoftware/SteamVR-for-Linux#63]
Currently, the text says the steam runtime script is located in: "~ /.steam/steam/ubuntu12_32/steam-runtime/run.sh", but I found the run.sh script in "~/.steam/ubuntu12_32/steam-runtime/run.sh".

Is there something wrong with my installation, or should the Readme.md be updated to reflect the accurate default location of the steam runtime script?

Running Steam beta on Ubuntu 17.04 x64

(Just checking... :D )

**Comment by kisak-valve** [comment]
Hello @jessedubord, the discrepancy you are seeing is because steam's folder layout from the distro-provided steam package for Ubuntu does not match the upstream package. The upstream package has steam in `~/.local/share/Steam` and a set of symlinks in `~/.steam`, including `~/.steam/steam` for many years.

The path provided in the readme.md is accurate for when using the Valve-provided steam package and  most other steam packages with the exception of what comes from Debian and distros that inherit packages from Debian such as Ubuntu and Linux Mint.
