### ISSUE TITLE
After 4 years (launch of HLA), I see no improvement in stability. Multitude of bugs (mongoose) and with numbers (109, 307, 483, 496, etc...).

### ISSUE THREAD

**Issue by Hicks79** [ValveSoftware/SteamVR-for-Linux#691]
Every 4 or 5 months I try Index again, hoping to have something stable.

It turns out that the fixes I have gotten have been thanks to users posting here (paths to sh files that are not correct, for example).

We continue with the mongoose problem. And a multitude of bugs with numbers (109, 307, 483, 496, etc...).

Any information from Valve at least?

Here a Report, maybe thats help. I cannot my devices update (BUG)

https://gist.github.com/Hicks79/24f3c6d0ee0b69741ec36ba04dcb7be1

**Comment by Hicks79** [comment]
I've noticed that after uninstalling/install SteamVr, and I've used the old "linux_v1.14" it goes almost perfect, at least steamvr seems to work and gives signal.

I can also play HLA (no mongoose-bugs)

The beta is getting worse and worse.

**Comment by Taiko2k** [comment]
> Any information from Valve at least?

Unfortunately there is a total lack of communication from Valve.

Even the Windows version of SteamVR has shockingly bad QA with bugs that don't get fixed and no communication.

**Comment by TTimo** [comment]
Hello,

Thank you for your report. Unfortunately you are reporting an issue against an old release of SteamVR, which will not receive further updates.

Please test against latest Steam client beta + SteamVR beta (currently 2.5.3) and open new reports. Please make sure to report one problem per issue, and to include the requested information from https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/issue_template.md so that we are able to investigate.

**Comment by kisak-valve** [comment]
Hello @TTimo, friendly note that the system report in the opening post is with SteamVR 2.5.3. Was there something more you were looking for here?

**Comment by TTimo** [comment]
We need minidumps, crash IDs and full logs. The system report has only partial coverage and isn't very useful. We're not requesting it in https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/issue_template.md anymore because of this.

This issue looks to be a meta for a number of other issues, hopefully the other ones get a good set of reports. There's no practical problem to work on here (#691) so I'm going to close it in an attempt to keep things tidy and focused on the latest beta.
