### ISSUE TITLE
VR mode can't be disabled without closing Steam

### ISSUE THREAD

**Issue by DataBeaver** [ValveSoftware/SteamVR-for-Linux#83]
#### Your system information
* Steam client version: 2017-12-01 15:05:56
* Distribution: Debian
* Graphics driver version: 387.22
* Gist for SteamVR System Information: https://gist.github.com/DataBeaver/4e11da6a3dd0d765267c1a4eb4b43842
* Opted into Steam client beta?: yes
* Opted into SteamVR beta?: yes
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Clicking the VR icon in the Steam client title bar works find and starts SteamVR.  However, even after I exit SteamVR the icon stays green.  Trying to click it again has no immediate effects but after a short while the Steam client crashes.

**Comment by ChristophHaag** [comment]
I think it's a steam client beta issue. The same happens with csgo to me, so I don't think it's even SteamVR specific. Opting out of the Steam client beta probably helps.

**Comment by h1z1** [comment]
Completely ignoring the fact that you can't click on exit because the overlay dropdown disappears, I've had this happen.  Look for stale vrserver / vrcompo*  processes.    For whatever reason if vrserver gets confused, it won't always shutdown properly.  Switching between direct and indirect mode for example sometimes caused it.   Regardless though, the Steam client thinks SteamVR is still running even though it really isn't.   For all I know it's a byproduct of some dbus fuckery in qt.  When I've seen it happen, the process was blocked on signals, didn't trace much further beyhond that.

ex:
```
$ pstree -pacl |grep -i vr
  |-vrserver,104411 -waitformonitor
  |   |-{vrserver},104414
  |   |-{vrserver},104415
  |   |-{vrserver},104416
  |   `-{vrserver},104418
```

There's no parent nor vrmonitor  yet steam still thought it was running.  

Another thing to look for are stale shm pipes, steam isn't cleaning those up properly either:

```
# ls -al /dev/shm/u1000-* | wc -l
116
~]# ipcs -a c steamvm | wc -l
199
~]# lsof /dev/shm/*  |grep steam | wc -l
36
```

I wouldn't kill them all since there's no easy way to tell which are still valid and not or look for ones that are growing.

**Comment by ChristophHaag** [comment]
Since recently this doesn't happen anymore for me. Can this be closed?

**Comment by DataBeaver** [comment]
I can confirm that the problem appears to be fixed in the Steam client build from 2018-02-14 16:01:48.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
